#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/docker-setup

- name: Restart Docker Daemon
  systemd_service:
    name: docker
    state: restarted
  become: true

- name: Start and Enable Docker Daemon
  systemd_service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  become: true
