#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/docker-setup

docker_users: [] # default variable for users added in the runtime eg. ubuntu, ec2-user etc.
docker_service_enabled: false # default variable for enabling docker service
docker_service_state: started # default variable for starting docker service




