---

- name: Greet Me!
  hosts: servers
  vars:
    my_name: "Yash"
  tasks:
    - name: Say Hello to Me
      #command: echo "Hello {{ my_name }}" 
      debug: # prints variables, expressions, or custom messages during execution
        msg: "Hello {{ my_name }}"