---

- name: Install Packages
  hosts: worker-ubuntu
  become: true

  vars: # variables
    packages: # refer it while looping
      - tree  # item1
      - unzip # item2
      - curl # item3
      - apache2 # item4
      - wget # item5
      - net-tools # item6
      - jq # item7
      - zip # item8
      - nginx # item9
      
  tasks:
    - name: Install
      loop: "{{ packages }}" # looping through the packages
      apt:
        name: "{{ item }}"
        state: present
    - name: Show Message
      loop: "{{ packages }}"
      debug:
          msg: "Installing {{ item }}"

      # - name: Start
      #   systemd:
      #     name: nginx
      #     state: "started"
      #     enabled: true

      

  