---

- name: Show Secrets
  hosts: servers
  become: true

  vars_files: # to import a file
    - secrets.yml
  tasks:
    - name: Show Username
      debug:
        msg: "The username is {{ username }}"
      #no_log: true # to not log the output
    - name: Show Password
      debug:
        msg: "The password is {{ password }}"
      #no_log: true # to not log the output
    - name: Show API Key
      debug:
        msg: "The API Key is {{ api_key }}"
      #no_log: true # to not log the output