- name: Upgrade all the Packages in RedHat
  dnf:
    name: "*"
    state: latest
- name: Add Docker Repository for RedHat
  #command: "curl -fsSL https://download.docker.com/linux/centos/docker-ce.repo"
  get_url:  # used to download files from the internet
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo # it will create the repo file in the destination path 
- name: Install Docker in RedHat
  dnf:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: latest